/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider, Wallet } from "fuels";
import { Interface, Contract } from "fuels";
import type {
  TestContractAbi,
  TestContractAbiInterface,
} from "../TestContractAbi";
const _abi = [
  {
    type: "function",
    inputs: [],
    name: "test_function",
    outputs: [
      {
        name: "",
        type: "struct test_struct",
        components: [
          {
            name: "v1",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "v2",
            type: "struct Vec",
            components: [
              {
                name: "buf",
                type: "struct RawVec",
                components: [
                  {
                    name: "ptr",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                  {
                    name: "cap",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
                typeArguments: [
                  {
                    name: "T",
                    type: "u64",
                    components: null,
                    typeArguments: null,
                  },
                ],
              },
              {
                name: "len",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
        ],
        typeArguments: null,
      },
    ],
  },
  {
    type: "function",
    inputs: [],
    name: "test_function_2",
    outputs: [
      {
        name: "",
        type: "struct Vec",
        components: [
          {
            name: "buf",
            type: "struct RawVec",
            components: [
              {
                name: "ptr",
                type: "u64",
                components: null,
                typeArguments: null,
              },
              {
                name: "cap",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
            typeArguments: [
              {
                name: "T",
                type: "u64",
                components: null,
                typeArguments: null,
              },
            ],
          },
          {
            name: "len",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
        typeArguments: [
          {
            name: "T",
            type: "u64",
            components: null,
            typeArguments: null,
          },
        ],
      },
    ],
  },
];

export class TestContractAbi__factory {
  static readonly abi = _abi;
  static createInterface(): TestContractAbiInterface {
    // return new Interface(_abi) as TestContractAbiInterface;
    // tried a workaround
    return new Interface(_abi) as any;
  }
  static connect(
    id: string,
    walletOrProvider: Wallet | Provider
  ): TestContractAbi {
    // return new Contract(id, _abi, walletOrProvider) as TestContractAbi;
    // tried a workaround
    return new Contract(id, _abi, walletOrProvider) as any;
  }
}
