/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestContractAbi } from "./TestContractAbi";

export { TestContractAbi__factory } from "./factories/TestContractAbi__factory";
